# Form implementation generated from reading ui file 'ventana_perfil_usuario.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(878, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font-family: \"Adwaita Sans\"; /* Establece la fuente */\n"
"     /* Establece el tamaño de la fuente */\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnCancelar = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        self.btnCancelar.setFont(font)
        self.btnCancelar.setStyleSheet("background-color: rgb(100, 132, 255);")
        self.btnCancelar.setObjectName("btnCancelar")
        self.gridLayout_2.addWidget(self.btnCancelar, 4, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.lblNombre = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.verticalLayout_24.addWidget(self.lblNombre)
        self.txtNombre = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setStyleSheet("background-color: rgb(221, 234, 183)rgb(255, 255, 255)")
        self.txtNombre.setObjectName("txtNombre")
        self.verticalLayout_24.addWidget(self.txtNombre)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.lblApellido = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblApellido.setFont(font)
        self.lblApellido.setObjectName("lblApellido")
        self.verticalLayout_34.addWidget(self.lblApellido)
        self.txtApellido = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtApellido.setFont(font)
        self.txtApellido.setStyleSheet("background-color: rgb(221, 234, 183)rgb(255, 255, 255)")
        self.txtApellido.setObjectName("txtApellido")
        self.verticalLayout_34.addWidget(self.txtApellido)
        self.verticalLayout_23.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.lblUsuario = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.verticalLayout_35.addWidget(self.lblUsuario)
        self.txtUsuario = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtUsuario.setFont(font)
        self.txtUsuario.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.txtUsuario.setObjectName("txtUsuario")
        self.verticalLayout_35.addWidget(self.txtUsuario)
        self.verticalLayout_23.addLayout(self.verticalLayout_35)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.lblOcupacion = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblOcupacion.setFont(font)
        self.lblOcupacion.setObjectName("lblOcupacion")
        self.verticalLayout_31.addWidget(self.lblOcupacion)
        self.txtOcupacion = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtOcupacion.setFont(font)
        self.txtOcupacion.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txtOcupacion.setObjectName("txtOcupacion")
        self.verticalLayout_31.addWidget(self.txtOcupacion)
        self.verticalLayout_23.addLayout(self.verticalLayout_31)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.lblEdad = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblEdad.setFont(font)
        self.lblEdad.setObjectName("lblEdad")
        self.verticalLayout_29.addWidget(self.lblEdad)
        self.txtEdad = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtEdad.setFont(font)
        self.txtEdad.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txtEdad.setObjectName("txtEdad")
        self.verticalLayout_29.addWidget(self.txtEdad)
        self.verticalLayout_23.addLayout(self.verticalLayout_29)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.lblPeso = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPeso.setFont(font)
        self.lblPeso.setObjectName("lblPeso")
        self.verticalLayout_32.addWidget(self.lblPeso)
        self.txtPeso = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtPeso.setFont(font)
        self.txtPeso.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txtPeso.setObjectName("txtPeso")
        self.verticalLayout_32.addWidget(self.txtPeso)
        self.verticalLayout_23.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.lblAltura = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAltura.setFont(font)
        self.lblAltura.setObjectName("lblAltura")
        self.verticalLayout_33.addWidget(self.lblAltura)
        self.txtAltura = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtAltura.setFont(font)
        self.txtAltura.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txtAltura.setObjectName("txtAltura")
        self.verticalLayout_33.addWidget(self.txtAltura)
        self.verticalLayout_23.addLayout(self.verticalLayout_33)
        self.gridLayout_2.addLayout(self.verticalLayout_23, 2, 0, 1, 1)
        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.gridLayout_2.addWidget(self.lblTitulo, 1, 0, 1, 1)
        self.btnRegistrar = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setStyleSheet("")
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.gridLayout_2.addWidget(self.btnRegistrar, 3, 0, 1, 1)
        self.btnRegresar = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        self.btnRegresar.setFont(font)
        self.btnRegresar.setObjectName("btnRegresar")
        self.gridLayout_2.addWidget(self.btnRegresar, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "App Habitos Saludables :"))
        self.btnCancelar.setText(_translate("Form", "Cancelar"))
        self.lblNombre.setText(_translate("Form", "Nombre:"))
        self.lblApellido.setText(_translate("Form", "Apellidos:"))
        self.lblUsuario.setText(_translate("Form", "Nombre de Usuario:"))
        self.lblOcupacion.setText(_translate("Form", "Ocupacion:"))
        self.lblEdad.setText(_translate("Form", "Edad:"))
        self.lblPeso.setText(_translate("Form", "Peso:"))
        self.lblAltura.setText(_translate("Form", "Altura:"))
        self.lblTitulo.setText(_translate("Form", "REGISTRO"))
        self.btnRegistrar.setText(_translate("Form", "Registrar"))
        self.btnRegresar.setText(_translate("Form", "Regresar"))
