# Form implementation generated from reading ui file 'VentanaRankingGeneral.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaRanking(object):
    def setupUi(self, ventanaRanking):
        ventanaRanking.setObjectName("ventanaRanking")
        ventanaRanking.resize(545, 567)
        self.centralwidget = QtWidgets.QWidget(parent=ventanaRanking)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblHolaUsuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblHolaUsuario.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblHolaUsuario.setFont(font)
        self.lblHolaUsuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblHolaUsuario.setObjectName("lblHolaUsuario")
        self.verticalLayout.addWidget(self.lblHolaUsuario)
        self.lblConsejo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblConsejo.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblConsejo.setFont(font)
        self.lblConsejo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblConsejo.setObjectName("lblConsejo")
        self.verticalLayout.addWidget(self.lblConsejo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableRanking = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableRanking.setMinimumSize(QtCore.QSize(499, 426))
        self.tableRanking.setMaximumSize(QtCore.QSize(499, 426))
        self.tableRanking.setObjectName("tableRanking")
        self.tableRanking.setColumnCount(0)
        self.tableRanking.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableRanking)
        self.lblPosicionPuntos = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPosicionPuntos.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPosicionPuntos.setFont(font)
        self.lblPosicionPuntos.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPosicionPuntos.setObjectName("lblPosicionPuntos")
        self.verticalLayout_2.addWidget(self.lblPosicionPuntos)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        ventanaRanking.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaRanking)
        QtCore.QMetaObject.connectSlotsByName(ventanaRanking)

    def retranslateUi(self, ventanaRanking):
        _translate = QtCore.QCoreApplication.translate
        ventanaRanking.setWindowTitle(_translate("ventanaRanking", "Ranking General"))
        self.lblHolaUsuario.setText(_translate("ventanaRanking", "🏆 Ranking General"))
        self.lblConsejo.setText(_translate("ventanaRanking", "Este es el ranking basado en puntos obtenidos por cada usuario."))
        self.lblPosicionPuntos.setText(_translate("ventanaRanking", "🧍 Tu posición: #5 - Tú (1210 pts)"))
