# Form implementation generated from reading ui file 'VentanaComunidades.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaComunidades(object):
    def setupUi(self, ventanaComunidades):
        ventanaComunidades.setObjectName("ventanaComunidades")
        ventanaComunidades.resize(1091, 566)
        ventanaComunidades.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#btnCrearUnaComunidad{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#btnCrearUnaComunidad:hover,\n"
"#btnCrearUnaComunidad:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=ventanaComunidades)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnCrearUnaComunidad = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCrearUnaComunidad.setObjectName("btnCrearUnaComunidad")
        self.horizontalLayout.addWidget(self.btnCrearUnaComunidad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listMisComunidades = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listMisComunidades.setMinimumSize(QtCore.QSize(500, 400))
        self.listMisComunidades.setObjectName("listMisComunidades")
        self.verticalLayout.addWidget(self.listMisComunidades)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cmbFiltroComunidades = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFiltroComunidades.setObjectName("cmbFiltroComunidades")
        self.cmbFiltroComunidades.addItem("")
        self.cmbFiltroComunidades.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbFiltroComunidades)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listTodasComunidades = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listTodasComunidades.setMinimumSize(QtCore.QSize(500, 400))
        self.listTodasComunidades.setObjectName("listTodasComunidades")
        self.verticalLayout_2.addWidget(self.listTodasComunidades)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        ventanaComunidades.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaComunidades)
        QtCore.QMetaObject.connectSlotsByName(ventanaComunidades)

    def retranslateUi(self, ventanaComunidades):
        _translate = QtCore.QCoreApplication.translate
        ventanaComunidades.setWindowTitle(_translate("ventanaComunidades", "Comunidades"))
        self.label.setText(_translate("ventanaComunidades", "Comunidades"))
        self.label_2.setText(_translate("ventanaComunidades", "Mis comunidades"))
        self.btnCrearUnaComunidad.setText(_translate("ventanaComunidades", "+ Crear una comunidad"))
        self.label_3.setText(_translate("ventanaComunidades", "Todas las comunidades"))
        self.label_4.setText(_translate("ventanaComunidades", "Filtrar por: "))
        self.cmbFiltroComunidades.setItemText(0, _translate("ventanaComunidades", "Todas"))
        self.cmbFiltroComunidades.setItemText(1, _translate("ventanaComunidades", "Unido"))
