# Form implementation generated from reading ui file 'perfil_usuario.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(545, 637)
        Form.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font-family: \"Adwaita Sans\"; /* Establece la fuente */\n"
"     /* Establece el tamaño de la fuente */\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.btnRegresar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        self.btnRegresar.setFont(font)
        self.btnRegresar.setObjectName("btnRegresar")
        self.gridLayout_3.addWidget(self.btnRegresar, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 17, 0, 1, 1)
        self.txtPeso = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtPeso.setFont(font)
        self.txtPeso.setReadOnly(True)
        self.txtPeso.setObjectName("txtPeso")
        self.gridLayout.addWidget(self.txtPeso, 13, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.txtEdad = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtEdad.setFont(font)
        self.txtEdad.setReadOnly(True)
        self.txtEdad.setObjectName("txtEdad")
        self.gridLayout.addWidget(self.txtEdad, 11, 0, 1, 1)
        self.txtApellido = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtApellido.setFont(font)
        self.txtApellido.setReadOnly(True)
        self.txtApellido.setObjectName("txtApellido")
        self.gridLayout.addWidget(self.txtApellido, 5, 0, 1, 1)
        self.txtOcupacion = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtOcupacion.setFont(font)
        self.txtOcupacion.setReadOnly(True)
        self.txtOcupacion.setObjectName("txtOcupacion")
        self.gridLayout.addWidget(self.txtOcupacion, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.txtAltura = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtAltura.setFont(font)
        self.txtAltura.setReadOnly(True)
        self.txtAltura.setObjectName("txtAltura")
        self.gridLayout.addWidget(self.txtAltura, 15, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.txtNombreUsuario = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNombreUsuario.setFont(font)
        self.txtNombreUsuario.setReadOnly(True)
        self.txtNombreUsuario.setObjectName("txtNombreUsuario")
        self.gridLayout.addWidget(self.txtNombreUsuario, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 14, 0, 1, 1)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setReadOnly(True)
        self.txtNombre.setObjectName("txtNombre")
        self.gridLayout.addWidget(self.txtNombre, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnRegresar.setText(_translate("Form", "Regresar"))
        self.label_2.setText(_translate("Form", "Nombre:"))
        self.label_3.setText(_translate("Form", "Apellido"))
        self.label_7.setText(_translate("Form", "Peso:"))
        self.label_6.setText(_translate("Form", "Edad:"))
        self.label_4.setText(_translate("Form", "Nombre usuario:"))
        self.label_5.setText(_translate("Form", "Ocupacion:"))
        self.label_8.setText(_translate("Form", "Altura:"))
        self.label.setText(_translate("Form", "PERFIL USUARIO"))
