# Form implementation generated from reading ui file 'VentanaNuevoHabito.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaRegistrarHabito(object):
    def setupUi(self, ventanaRegistrarHabito):
        ventanaRegistrarHabito.setObjectName("ventanaRegistrarHabito")
        ventanaRegistrarHabito.resize(715, 478)
        ventanaRegistrarHabito.setStyleSheet("\n"
"QCheckBox {\n"
"    spacing: 8px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnVolverIniciarSesion{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=ventanaRegistrarHabito)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        font.setBold(True)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout_7.addWidget(self.lblTitulo)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblNombre = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.verticalLayout_2.addWidget(self.lblNombre)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNombre.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setObjectName("txtNombre")
        self.verticalLayout_2.addWidget(self.txtNombre)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCategoria = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblCategoria.setFont(font)
        self.lblCategoria.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblCategoria.setObjectName("lblCategoria")
        self.verticalLayout.addWidget(self.lblCategoria)
        self.cmbCategoria = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbCategoria.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbCategoria.setFont(font)
        self.cmbCategoria.setObjectName("cmbCategoria")
        self.cmbCategoria.addItem("")
        self.cmbCategoria.addItem("")
        self.cmbCategoria.addItem("")
        self.cmbCategoria.addItem("")
        self.cmbCategoria.addItem("")
        self.cmbCategoria.addItem("")
        self.verticalLayout.addWidget(self.cmbCategoria)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblFrecuencia = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFrecuencia.setFont(font)
        self.lblFrecuencia.setObjectName("lblFrecuencia")
        self.verticalLayout_3.addWidget(self.lblFrecuencia)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkLunes = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkLunes.setFont(font)
        self.checkLunes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkLunes.setObjectName("checkLunes")
        self.gridLayout_2.addWidget(self.checkLunes, 0, 0, 1, 1)
        self.checkViernes = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkViernes.setFont(font)
        self.checkViernes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkViernes.setObjectName("checkViernes")
        self.gridLayout_2.addWidget(self.checkViernes, 0, 4, 1, 1)
        self.checkDomingo = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkDomingo.setFont(font)
        self.checkDomingo.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkDomingo.setObjectName("checkDomingo")
        self.gridLayout_2.addWidget(self.checkDomingo, 0, 7, 1, 1)
        self.checkMartes = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkMartes.setFont(font)
        self.checkMartes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkMartes.setObjectName("checkMartes")
        self.gridLayout_2.addWidget(self.checkMartes, 0, 1, 1, 1)
        self.checkMiercoles = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkMiercoles.setFont(font)
        self.checkMiercoles.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkMiercoles.setObjectName("checkMiercoles")
        self.gridLayout_2.addWidget(self.checkMiercoles, 0, 2, 1, 1)
        self.checkJueves = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkJueves.setFont(font)
        self.checkJueves.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkJueves.setObjectName("checkJueves")
        self.gridLayout_2.addWidget(self.checkJueves, 0, 3, 1, 1)
        self.checkSabado = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkSabado.setFont(font)
        self.checkSabado.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkSabado.setObjectName("checkSabado")
        self.gridLayout_2.addWidget(self.checkSabado, 0, 6, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnGuardarHabito = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGuardarHabito.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGuardarHabito.setFont(font)
        self.btnGuardarHabito.setStyleSheet("")
        self.btnGuardarHabito.setObjectName("btnGuardarHabito")
        self.verticalLayout_5.addWidget(self.btnGuardarHabito)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setStyleSheet("")
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout_5.addWidget(self.btnCancelar)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        ventanaRegistrarHabito.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaRegistrarHabito)
        QtCore.QMetaObject.connectSlotsByName(ventanaRegistrarHabito)

    def retranslateUi(self, ventanaRegistrarHabito):
        _translate = QtCore.QCoreApplication.translate
        ventanaRegistrarHabito.setWindowTitle(_translate("ventanaRegistrarHabito", "Habito"))
        self.lblTitulo.setText(_translate("ventanaRegistrarHabito", "Habito"))
        self.lblNombre.setText(_translate("ventanaRegistrarHabito", "Nombre:"))
        self.lblCategoria.setText(_translate("ventanaRegistrarHabito", "Categoria:"))
        self.cmbCategoria.setItemText(0, _translate("ventanaRegistrarHabito", "Planificar comidas balanceadas."))
        self.cmbCategoria.setItemText(1, _translate("ventanaRegistrarHabito", "Actividad Física"))
        self.cmbCategoria.setItemText(2, _translate("ventanaRegistrarHabito", "Beber suficiente agua"))
        self.cmbCategoria.setItemText(3, _translate("ventanaRegistrarHabito", "Meditar 5-10 minutos al día."))
        self.cmbCategoria.setItemText(4, _translate("ventanaRegistrarHabito", "Comer proteínas magras"))
        self.cmbCategoria.setItemText(5, _translate("ventanaRegistrarHabito", "Sueño Reparador"))
        self.lblFrecuencia.setText(_translate("ventanaRegistrarHabito", "¿Qué días seguirás este hábito?"))
        self.checkLunes.setText(_translate("ventanaRegistrarHabito", "Lunes"))
        self.checkViernes.setText(_translate("ventanaRegistrarHabito", "Viernes"))
        self.checkDomingo.setText(_translate("ventanaRegistrarHabito", "Domingo"))
        self.checkMartes.setText(_translate("ventanaRegistrarHabito", "Martes"))
        self.checkMiercoles.setText(_translate("ventanaRegistrarHabito", "Miercoles"))
        self.checkJueves.setText(_translate("ventanaRegistrarHabito", "Jueves"))
        self.checkSabado.setText(_translate("ventanaRegistrarHabito", "Sabado"))
        self.btnGuardarHabito.setToolTip(_translate("ventanaRegistrarHabito", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Registrar</span></p></body></html>"))
        self.btnGuardarHabito.setWhatsThis(_translate("ventanaRegistrarHabito", "<html><head/><body><p align=\"center\">Registrar</p></body></html>"))
        self.btnGuardarHabito.setText(_translate("ventanaRegistrarHabito", "Guardar habito"))
        self.btnCancelar.setText(_translate("ventanaRegistrarHabito", "Cancelar"))
