# Form implementation generated from reading ui file 'VentanaHabitos.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaHabitos(object):
    def setupUi(self, ventanaHabitos):
        ventanaHabitos.setObjectName("ventanaHabitos")
        ventanaHabitos.resize(1000, 579)
        self.centralwidget = QtWidgets.QWidget(parent=ventanaHabitos)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarioHabitos = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarioHabitos.setGeometry(QtCore.QRect(30, 40, 350, 350))
        self.calendarioHabitos.setFirstDayOfWeek(QtCore.Qt.DayOfWeek.Monday)
        self.calendarioHabitos.setGridVisible(False)
        self.calendarioHabitos.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarioHabitos.setObjectName("calendarioHabitos")
        self.listHabitos = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listHabitos.setGeometry(QtCore.QRect(410, 40, 551, 421))
        self.listHabitos.setObjectName("listHabitos")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 500, 521, 27))
        self.pushButton.setObjectName("pushButton")
        ventanaHabitos.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaHabitos)
        QtCore.QMetaObject.connectSlotsByName(ventanaHabitos)

    def retranslateUi(self, ventanaHabitos):
        _translate = QtCore.QCoreApplication.translate
        ventanaHabitos.setWindowTitle(_translate("ventanaHabitos", "MainWindow"))
        self.pushButton.setText(_translate("ventanaHabitos", "Agregar un habito"))
