# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 773)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    font-family: \"Adwaita Sans\"; /* Establece la fuente */\n"
"     /* Establece el tamaño de la fuente */\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_titulo_principal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_titulo_principal.setGeometry(QtCore.QRect(230, 10, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_titulo_principal.setFont(font)
        self.lbl_titulo_principal.setObjectName("lbl_titulo_principal")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 461, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("iconos/fondoPrincipalV2.jpg"))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(490, 170, 391, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.txt_desafios_Pendientes = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_desafios_Pendientes.setFont(font)
        self.txt_desafios_Pendientes.setObjectName("txt_desafios_Pendientes")
        self.gridLayout.addWidget(self.txt_desafios_Pendientes, 7, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.txt_Ranking = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Ranking.setFont(font)
        self.txt_Ranking.setObjectName("txt_Ranking")
        self.gridLayout.addWidget(self.txt_Ranking, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 8, 1, 1, 1)
        self.txt_Habitos_Pendientes = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Habitos_Pendientes.setFont(font)
        self.txt_Habitos_Pendientes.setObjectName("txt_Habitos_Pendientes")
        self.gridLayout.addWidget(self.txt_Habitos_Pendientes, 6, 2, 1, 1)
        self.txt_userName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_userName.setFont(font)
        self.txt_userName.setObjectName("txt_userName")
        self.gridLayout.addWidget(self.txt_userName, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 2)
        self.progressBar_Habitos = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.progressBar_Habitos.setProperty("value", 24)
        self.progressBar_Habitos.setObjectName("progressBar_Habitos")
        self.gridLayout.addWidget(self.progressBar_Habitos, 5, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 550, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(50, 50))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.LeftToolBarArea, self.toolBar)
        self.action_Icono_Habitos_Saludables = QtGui.QAction(parent=MainWindow)
        self.action_Icono_Habitos_Saludables.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("Habitos_Saludables")
        self.action_Icono_Habitos_Saludables.setIcon(icon)
        self.action_Icono_Habitos_Saludables.setObjectName("action_Icono_Habitos_Saludables")
        self.action_Icono_Logros = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("Logros")
        self.action_Icono_Logros.setIcon(icon)
        self.action_Icono_Logros.setObjectName("action_Icono_Logros")
        self.action_Icono_Ranking = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("Ranking")
        self.action_Icono_Ranking.setIcon(icon)
        self.action_Icono_Ranking.setObjectName("action_Icono_Ranking")
        self.action_Icono_Comunidad = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("Comunidad")
        self.action_Icono_Comunidad.setIcon(icon)
        self.action_Icono_Comunidad.setObjectName("action_Icono_Comunidad")
        self.action_Icono_Perfil_Usuario = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/usuarios.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_Icono_Perfil_Usuario.setIcon(icon)
        self.action_Icono_Perfil_Usuario.setObjectName("action_Icono_Perfil_Usuario")
        self.action_Icono_Cerrar_Sesion = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("Cerrar_Sesion")
        self.action_Icono_Cerrar_Sesion.setIcon(icon)
        self.action_Icono_Cerrar_Sesion.setObjectName("action_Icono_Cerrar_Sesion")
        self.action_item_Habitos_Saludables = QtGui.QAction(parent=MainWindow)
        self.action_item_Habitos_Saludables.setObjectName("action_item_Habitos_Saludables")
        self.actionLogros = QtGui.QAction(parent=MainWindow)
        self.actionLogros.setObjectName("actionLogros")
        self.actionRanking = QtGui.QAction(parent=MainWindow)
        self.actionRanking.setObjectName("actionRanking")
        self.actionDesaf_os = QtGui.QAction(parent=MainWindow)
        self.actionDesaf_os.setObjectName("actionDesaf_os")
        self.actionComunidad = QtGui.QAction(parent=MainWindow)
        self.actionComunidad.setObjectName("actionComunidad")
        self.actionPerfil_Usuario = QtGui.QAction(parent=MainWindow)
        self.actionPerfil_Usuario.setObjectName("actionPerfil_Usuario")
        self.actionCerrar_Sesion = QtGui.QAction(parent=MainWindow)
        self.actionCerrar_Sesion.setObjectName("actionCerrar_Sesion")
        self.menuMenu.addAction(self.action_item_Habitos_Saludables)
        self.menuMenu.addAction(self.actionLogros)
        self.menuMenu.addAction(self.actionRanking)
        self.menuMenu.addAction(self.actionDesaf_os)
        self.menuMenu.addAction(self.actionComunidad)
        self.menuMenu.addAction(self.actionPerfil_Usuario)
        self.menuMenu.addAction(self.actionCerrar_Sesion)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.toolBar.addAction(self.action_Icono_Habitos_Saludables)
        self.toolBar.addAction(self.action_Icono_Logros)
        self.toolBar.addAction(self.action_Icono_Ranking)
        self.toolBar.addAction(self.action_Icono_Comunidad)
        self.toolBar.addAction(self.action_Icono_Perfil_Usuario)
        self.toolBar.addAction(self.action_Icono_Cerrar_Sesion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SISTEMA HABITOS SALUDABLES :: Menú Principal"))
        self.lbl_titulo_principal.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\"> Hábitos Saludables</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Infromación de inicio rápido"))
        self.label_3.setText(_translate("MainWindow", "Nivel:"))
        self.label_4.setText(_translate("MainWindow", "Avance de habitos:"))
        self.label_5.setText(_translate("MainWindow", "Habitos Pendientes:"))
        self.label_6.setText(_translate("MainWindow", "Desafios Pendientes"))
        self.label_7.setText(_translate("MainWindow", "Usuario:"))
        self.pushButton.setText(_translate("MainWindow", "Crear un nuevo habito"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Icono_Habitos_Saludables.setText(_translate("MainWindow", "Habitos Saludables"))
        self.action_Icono_Logros.setText(_translate("MainWindow", "Logros"))
        self.action_Icono_Ranking.setText(_translate("MainWindow", "Ranking"))
        self.action_Icono_Comunidad.setText(_translate("MainWindow", "Comunidad"))
        self.action_Icono_Perfil_Usuario.setText(_translate("MainWindow", "Perfil"))
        self.action_Icono_Perfil_Usuario.setToolTip(_translate("MainWindow", "Perfil_Usuario"))
        self.action_Icono_Cerrar_Sesion.setText(_translate("MainWindow", "Cerrar Sesion"))
        self.action_item_Habitos_Saludables.setText(_translate("MainWindow", "Habitos_Saludables"))
        self.actionLogros.setText(_translate("MainWindow", "Logros"))
        self.actionRanking.setText(_translate("MainWindow", "Ranking"))
        self.actionDesaf_os.setText(_translate("MainWindow", "Desafíos"))
        self.actionComunidad.setText(_translate("MainWindow", "Comunidad"))
        self.actionPerfil_Usuario.setText(_translate("MainWindow", "Perfil_Usuario"))
        self.actionCerrar_Sesion.setText(_translate("MainWindow", "Cerrar_Sesion"))
