# Form implementation generated from reading ui file 'VentanaHabitos.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaHabitos(object):
    def setupUi(self, ventanaHabitos):
        ventanaHabitos.setObjectName("ventanaHabitos")
        ventanaHabitos.resize(1029, 584)
        ventanaHabitos.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCalendarWidget {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 10px;\n"
"    font-family: Arial;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: #2c3e50;\n"
"    background-color: #ecf0f1;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    padding: 5px 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #d0d3d4;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox {\n"
"    width: 70px;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #f7f9fa;\n"
"    border-bottom: 1px solid #dcdcdc;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    selection-background-color: #27ae60;\n"
"    selection-color: white;\n"
"    background-color: #ffffff;\n"
"    gridline-color: #ecf0f1;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    font-size: 10pt;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView::item:hover {\n"
"    background-color: rgb(116, 162, 255);\n"
"    color: black;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView::item:selected {\n"
"    background-color: rgb(80, 127, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView::item:disabled {\n"
"    color: #bdc3c7;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QCalendarWidget QMenu::item {\n"
"    padding: 5px 15px;\n"
"    background-color: transparent;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #d0d3d4;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QPushButton#btnVolverIniciarSesion{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnVolverIniciarSesion:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnVolverIniciarSesion:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"QListWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=ventanaHabitos)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(35)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.calendarioHabitos = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarioHabitos.setMinimumSize(QtCore.QSize(400, 400))
        self.calendarioHabitos.setMaximumSize(QtCore.QSize(400, 400))
        self.calendarioHabitos.setFirstDayOfWeek(QtCore.Qt.DayOfWeek.Monday)
        self.calendarioHabitos.setGridVisible(False)
        self.calendarioHabitos.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarioHabitos.setObjectName("calendarioHabitos")
        self.verticalLayout.addWidget(self.calendarioHabitos)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listHabitos = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listHabitos.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listHabitos.setFont(font)
        self.listHabitos.setObjectName("listHabitos")
        self.verticalLayout_2.addWidget(self.listHabitos)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.btnAgregarUnHabito = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregarUnHabito.setMinimumSize(QtCore.QSize(0, 35))
        self.btnAgregarUnHabito.setObjectName("btnAgregarUnHabito")
        self.verticalLayout_3.addWidget(self.btnAgregarUnHabito)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        ventanaHabitos.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaHabitos)
        QtCore.QMetaObject.connectSlotsByName(ventanaHabitos)

    def retranslateUi(self, ventanaHabitos):
        _translate = QtCore.QCoreApplication.translate
        ventanaHabitos.setWindowTitle(_translate("ventanaHabitos", "Habitos"))
        self.label_2.setText(_translate("ventanaHabitos", "Calendario"))
        self.label.setText(_translate("ventanaHabitos", "Mis habitos"))
        self.btnAgregarUnHabito.setText(_translate("ventanaHabitos", "Agregar un habito"))
